### PR TITLE
Preliminary term resize handling

### PR DESCRIPTION
**Pull request by adder46**
I noticed that pyhstr does not handle term resize. In my other curses program, it is enough to catch the `KEY_RESIZE` code and redraw the screen, however, this is not true with Python curses. I searched online a bit, and it seems that libncurses needs to be compiled with a special flag:

> This is right, but only when ncurses is compiled with --enable-sigwinch. In particular, the libncurses in Debian and Ubuntu doesn't have that turned on; I'm not sure why. 

More on that [here](https://stackoverflow.com/questions/5161552/python-curses-handling-window-terminal-resize).

Further investigation led to the idea of trapping `SIGWINCH`, and this PR uses that approach. However, I'm not 100% sure this is the way to go. Also, resizing/redrawing behavior is a bit weird.

@Akuli, what do you think?

### CODE REVIEW

**Comment by Akuli** [comment]
In the past, I have compiled curses programs on Debian-based distros that use KEY_RESIZE. Their resize handling works.

**Comment by Akuli** [comment]
Looking at that stackoverflow question, the answer you quoted is very old, and someone replied that it works on Ubuntu 12.04 (from 2012).

**Comment by Akuli** [comment]
Looking at `__main__.py`, you have written the `while True` loop so that getting an unknown `user_input` does nothing. Here's the end of the loop:

https://github.com/adder46/pyhstr/blob/c100283a060d71403f455779700fac27146601d6/pyhstr/__main__.py#L111-L119

So if `getch()` returns `KEY_RESIZE`, none of the conditions in this `if ... elif ... elif` code match, so the screen does not get redrawn.

Last time I worked with curses, I was surprised that the resizing just worked, without having to write any code to handle it. That program redraws the screen every time a key is pressed, regardless of which key it is:

```c
    while(true) {
        /* ... */

        draw_game(&gs, landings);
        refresh();

        switch(getch()) {
            /* ... '/
        }
    }
```

**Comment by adder46** [comment]
No, I've explicitly handled that when I first tried to catch KEY_RESIZE:

        elif user_input == curses.KEY_RESIZE:
            app.stdscr.clear()
            app.user_interface.populate_screen()
            
But nothing happens. I tried to: `q/"spam"` inside that elif, and it seems that the code is not being run at all.

**Comment by Akuli** [comment]
you forgot to refresh

**Comment by Akuli** [comment]
Let me try to `q` this thing and see if I can find the problem

**Comment by Akuli** [comment]
For some reason, the `except curses.error` part of the code runs when I resize the window

**Comment by adder46** [comment]
I came across [this](https://bugs.python.org/issue3948) and [this](https://bugs.python.org/issue2675).

**Comment by Akuli** [comment]
IMO the easiest fix would be to add redrawing code to `except curses.error`, along with a comment saying that it's there because of readline.

**Pull request closed without merging**
